USE ROLE ACCOUNTADMIN;

-- Remove agent from Snowflake Intelligence before dropping schema
ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
  DROP AGENT IF EXISTS CUSTOMER_DEMOS.ARC.ARC_AGENT;

DROP SCHEMA IF EXISTS CUSTOMER_DEMOS.ARC CASCADE;
DROP WAREHOUSE IF EXISTS ARC_WH;
DROP ROLE IF EXISTS ARC_USER;
